[build-system]
requires = [
    "wheel",
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "pybind11>=2.6.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/awkward_xaod_bridge/_version.py"
